app = "vaadin-docs-mcp-server"
primary_region = "sjc" # San Jose, CA - change as needed

[build]
  dockerfile = "Dockerfile"

[env]
  # Environment variables will be set through fly secrets
  # Do not put sensitive information here

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"
