app = "vaadin-mcp"

[build]
  dockerfile = "Dockerfile"

[env]
  HTTP_PORT = "8080"
  REST_SERVER_URL = "https://vaadin-docs-search.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[http_service.concurrency]
  type = "connections"
  hard_limit = 1000
  soft_limit = 500

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"
  protocol = "http"