name: Deploy REST Server to Fly.io

on:
  push:
    branches:
      - main
    paths:
      - 'packages/rest-server/**'
      - '.github/workflows/deploy-rest-server.yml'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy REST Server
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Cache Vaadin docs repository
        uses: actions/cache@v4
        with:
          path: ./packages/1-asciidoc-converter/vaadin-docs
          key: vaadin-docs-latest-${{ github.run_id }}
          restore-keys: |
            vaadin-docs-latest-
            vaadin-docs-
      
      - name: Install workspace dependencies
        run: bun install
      
      - name: Build packages
        run: bun run build
      
      - name: Convert AsciiDoc to Markdown
        working-directory: ./packages/1-asciidoc-converter
        run: |
          echo "🔄 Converting AsciiDoc files to Markdown for production..."
          bun run convert
          echo "✅ AsciiDoc conversion completed"
      
      - name: Build REST server
        working-directory: ./packages/rest-server
        run: bun run build
      
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only --config packages/rest-server/fly.toml --dockerfile packages/rest-server/Dockerfile
